#!/usr/bin/env python3
"""Wrap the standalone .exe into a single Inno Setup installer.

    python build_installer.py

Reads the version from src/s2p_tool/__init__.py, finds the matching
releases/s2p-<version>-win64.exe (build it first with build_exe.py), generates
an Inno Setup script and compiles it to releases/s2p-setup-<version>.exe.

The installer is a single distributable file. It installs per-user (no admin
prompt), creates Start-Menu and optional desktop shortcuts, registers a proper
uninstaller, and puts the app in a stable location instead of leaving a loose
exe that antivirus / restricted machines often refuse to launch.

Requires Inno Setup 6.3+ (ISCC.exe). Install with:
    winget install --id JRSoftware.InnoSetup -e
"""
import os
import re
import subprocess
import sys
from pathlib import Path

PUBLISHER = "Kaan AKCAN"


def get_version() -> str:
    txt = Path("src/s2p_tool/__init__.py").read_text(encoding="utf-8")
    m = re.search(r'__version__\s*=\s*"([^"]+)"', txt)
    if not m:
        raise ValueError("Cannot find __version__ in src/s2p_tool/__init__.py")
    return m.group(1)


def find_iscc() -> str:
    """Locate ISCC.exe (Inno Setup compiler) across common install roots."""
    candidates = [
        Path(os.environ.get("LOCALAPPDATA", "")) / "Programs/Inno Setup 6/ISCC.exe",
        Path(r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe"),
        Path(r"C:\Program Files\Inno Setup 6\ISCC.exe"),
    ]
    for c in candidates:
        if c.is_file():
            return str(c)
    raise FileNotFoundError(
        "ISCC.exe (Inno Setup) bulunamadı. Kur: "
        "winget install --id JRSoftware.InnoSetup -e")


def main() -> None:
    version = get_version()
    releases = Path("releases").resolve()
    exe = releases / f"chiplens-{version}-win64.exe"
    if not exe.is_file():
        print(f"✗ {exe.name} yok — önce: python build_exe.py")
        sys.exit(1)
    ico = Path("assets/chiplens.ico").resolve()

    iscc = find_iscc()
    iss = releases / f"chiplens-{version}.iss"
    iss.write_text(f"""; Auto-generated by build_installer.py — do not edit by hand.
[Setup]
AppId={{{{4C7F2E1A-9B3D-4E62-A1F8-6D5C0B2E9A47}}}}
AppName=ChipLens
AppVersion={version}
AppPublisher={PUBLISHER}
DefaultDirName={{autopf}}\\ChipLens
DefaultGroupName=ChipLens
DisableProgramGroupPage=yes
DisableDirPage=auto
SetupIconFile={ico}
UninstallDisplayIcon={{app}}\\ChipLens.exe
OutputDir={releases}
OutputBaseFilename=chiplens-setup-{version}
Compression=lzma2/max
SolidCompression=yes
PrivilegesRequired=lowest
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
WizardStyle=modern

[Languages]
Name: "tr"; MessagesFile: "compiler:Languages\\Turkish.isl"
Name: "en"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Masaüstü kısayolu oluştur"; GroupDescription: "Ek kısayollar:"

[Files]
Source: "{exe}"; DestDir: "{{app}}"; DestName: "ChipLens.exe"; Flags: ignoreversion

[Icons]
Name: "{{group}}\\ChipLens"; Filename: "{{app}}\\ChipLens.exe"
Name: "{{autodesktop}}\\ChipLens"; Filename: "{{app}}\\ChipLens.exe"; Tasks: desktopicon

[Run]
Filename: "{{app}}\\ChipLens.exe"; Description: "ChipLens'i çalıştır"; Flags: nowait postinstall skipifsilent
""", encoding="utf-8")

    print(f"[*] Inno Setup derleniyor (v{version})...")
    r = subprocess.run([iscc, str(iss)])
    if r.returncode != 0:
        print(f"✗ ISCC {r.returncode} ile başarısız")
        sys.exit(1)

    out = releases / f"s2p-setup-{version}.exe"
    iss.unlink(missing_ok=True)
    if out.is_file():
        print(f"\n✓ SUCCESS: {out}  ({out.stat().st_size/1048576:.1f} MB)")
    else:
        print("✗ setup exe üretilmedi"); sys.exit(1)


if __name__ == "__main__":
    main()
